import sqlite3
import shutil
import os

DB_NAME = os.path.join(os.path.dirname(os.path.abspath(__file__)), "streetfixx.db")
BACKUP_NAME = "streetfixx_backup.db"

def get_db_connection():
    conn = sqlite3.connect(DB_NAME)
    conn.row_factory = sqlite3.Row
    return conn

def migrate():
    print("Starting safe database migration...")
    
    # 1. Backup the database
    if os.path.exists(DB_NAME):
        shutil.copy(DB_NAME, BACKUP_NAME)
        print(f"Backup created: {BACKUP_NAME}")
    else:
        print("Database file not found.")
        return

    conn = get_db_connection()
    cursor = conn.cursor()

    try:
        # 2. Check existing columns
        print("Inspecting existing 'issues' table...")
        cursor.execute("PRAGMA table_info(issues)")
        columns = cursor.fetchall()
        col_names = [col['name'] for col in columns]
        print(f"Existing columns: {col_names}")

        if 'issue_id' not in col_names:
            print("Migration not needed: 'issue_id' column not found.")
            return

        # 3. Rename old table
        print("Renaming 'issues' to 'issues_old'...")
        cursor.execute("ALTER TABLE issues RENAME TO issues_old")

        # 4. Create new table without issue_id
        # Schema based on db.py but ensuring no issue_id
        print("Creating new 'issues' table...")
        cursor.execute('''
            CREATE TABLE issues (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER,
                title TEXT NOT NULL,
                description TEXT,
                category TEXT,
                location TEXT,
                latitude REAL,
                longitude REAL,
                image_url TEXT,
                completion_image TEXT,
                completed_at TIMESTAMP,
                completed_by INTEGER,
                status TEXT DEFAULT 'Pending',
                assigned_to INTEGER,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (user_id) REFERENCES users (id),
                FOREIGN KEY (assigned_to) REFERENCES users (id),
                FOREIGN KEY (completed_by) REFERENCES users (id)
            )
        ''')

        # 5. Copy data
        # We need to map columns from old table to new table.
        # Common columns: user_id, title, description, category, location, latitude, longitude, image_url, 
        # completion_image, completed_at, completed_by, status, assigned_to, created_at
        
        # Determine which columns to copy. We'll intersect new schema columns with old columns.
        new_cols = ['id', 'user_id', 'title', 'description', 'category', 'location', 'latitude', 'longitude', 
                    'image_url', 'completion_image', 'completed_at', 'completed_by', 'status', 'assigned_to', 'created_at']
        
        # Build the INSERT SELECT statement dynamically based on available columns in old table
        cols_to_copy = [c for c in new_cols if c in col_names]
        
        # If 'id' is not in old columns but 'issue_id' is, maybe we want to map issue_id -> id?
        # User said "Remove issue_id column completely", "Use only id".
        # If 'id' exists in old table, we preserve it. 
        # If 'id' does NOT exist in old table (rare if it was standard sqlite), but 'issue_id' was the PK,
        # we might lose ID continuity if we don't map it.
        # Let's assume 'id' exists (rowid usually aliased if integer primary key).
        # But if 'issue_id' was the explicit PK, then 'id' might not be in col_names explicitly if inspecting via PRAGMA?
        # Actually PRAGMA table_info shows all columns defined.
        
        # Special handling: if 'id' is missing in old table, but 'issue_id' is present, should we map issue_id to id?
        # The user said "remove issue_id column completely". 
        # If the old table has 'id', we copy it.
        # If the old table ONLY has 'issue_id' as PK and no 'id' column, we should probably migrate 'issue_id' values to 'id' 
        # so existing references (if any) or just history is preserved.
        # BUT the user said "Remove issue_id column completely".
        # Let's trust that 'id' exists or will be autogenerated.
        # However, to be safe, if 'id' is in col_names, we copy it.
        
        cols_str = ", ".join(cols_to_copy)
        print(f"Copying data for columns: {cols_str}")
        
        cursor.execute(f"INSERT INTO issues ({cols_str}) SELECT {cols_str} FROM issues_old")
        
        # 6. Drop old table
        print("Dropping 'issues_old' table...")
        cursor.execute("DROP TABLE issues_old")
        
        conn.commit()
        print("Migration successful! 'issue_id' removed.")

    except Exception as e:
        print(f"Migration failed: {e}")
        conn.rollback()
        print("Rolled back changes. Restoring from backup...")
        # Since we are inside a transaction, rollback handles DB state.
        # We also have the file backup if things went really south (like modifying file during copy).
    finally:
        conn.close()

if __name__ == '__main__':
    migrate()
